### ISSUE TITLE
Add playwright test cases

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/dom-to-html#2]
The easiest may be to use react and playwright to make the test.

We need at the end an html page containing a SVG and a Canvas and check that on all the browser we obtain a HTML code that contains base64 encoded images

**Comment by targos** [comment]
I suggest to use Playwright component testing with React.

**Comment by targos** [comment]
https://playwright.dev/docs/test-components

**Comment by lpatiny** [comment]
We need to check as well that the image size looks ok.
