### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/dom-to-html#7]
Expose a new function that allows to copy a dom element to clipboard.

It is clear how to do with chrome, safari and edge but we don't know about firefox (but if it does not work we leave it like that).

`copyAsHtml(domElement, options)`

options:
- error: default value: `(e) => (alert(e.toString())`

Currently we can create an error in the case of firefox.

**Comment by wadjih-bencheikh18** [comment]
does webkit (safari) support javascript clipboard?

**Comment by lpatiny** [comment]
I guess it should be working indeed. At least based on https://web.dev/async-clipboard/

But there is a specific message concerning webkit here:

https://web.dev/async-clipboard/

And currently in another project it does not work for us:

https://github.com/cheminfo/nmrium/issues/1682

**Comment by stropitek** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#browser_compatibility

Have you seen the notes about compatibility for Safari?

> ![image](https://user-images.githubusercontent.com/4118690/183367715-2074dc98-c485-4dba-a551-314d0a0e5271.png)

**Comment by wadjih-bencheikh18** [comment]
> Have you seen the notes about compatibility for Safari?

yes and still no compatible
